import Layout from "@/components/Layout";
import Head from "next/head";
import Image from "next/image";
import profilePic from "../../public/images/profile/developer-pic-1.png";
import AnimatedText from "@/components/AnimatedText";
import Link from "next/link";
import { LinkArrow } from "@/components/icons";

export default function Home() {
  return (
    <>
      <Head>
        <title>Sobuj</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <main className="flex items-center w-full min-h-screen text-dark">
        <Layout className="pt-0">
          <div className="w-full flex items-center justify-between">
            {/* image container */}
            <div className="w-1/2">
              <Image src={profilePic} alt="sobuj" className="w-full h-auto" />
            </div>
            {/* text in home */}
            <div className="w-1/2 flex flex-col items-center self-center">
              <AnimatedText text="Turning Vision Into Reality With Code ."></AnimatedText>
              <p className="my-4 text-base font-medium">
                As a skilled full-stack developer, I am dedicated to turning
                ideas into innovative web applications. Explore my latest
                projects and articles, showcasing my expertise in React.js and
                web development.
              </p>
              <div className="flex items-center self-start mt-2">
                <Link
                  href="/portfolio.pdf"
                  target="_blank"
                  className="flex items-center bg-dark text-light p-2.5 px-5 rounded-lg font-semibold text-lg hover:bg-light hover:text-dark border-2 border-solid border-transparent hover:border-dark"
                  download={true}>
                  Resume <LinkArrow className="!w-6 ml-1"></LinkArrow>
                </Link>
                <Link
                  href="sobujahmed124@gmail.com"
                  target="_blank"
                  className="ml-4 font-medium capitalize text-lg text-dark underline hover:bg-dark hover:text-light p-3 px-7 rounded-lg">
                  Contact
                </Link>
              </div>
            </div>
          </div>
        </Layout>
      </main>
    </>
  );
}
